### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by erikbozic** [erikbozic/tarok-scoreboard#2]
- [x] Proper endpoints for statistics. (per game, team, player, game type, modifiers?)
- [ ] Validation on team creation
- [ ] Implement a proper logging solution. Now it's only console output.
- [x] When creating a game actually check if the specified players are a part of the team.
- [x] Database optimiziations (bulk inserts, less round trips)
- [x] Cleanup responses from any uneeded or sensitive data (hashsed passwords, unneeded ids...)
